version: '3.7'
services:
  proxy:
    image: nginx
    volumes:
      - ./share/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${PORT}:7778"
  web:
    build: .
    restart: always
    volumes:
      - ./${FLAGFILE}:/flag:ro
